package com.alerts.Week3Logic;

public enum AlertType {
    BLOOD_PRESSURE_TREND,
    BLOOD_PRESSURE_CRITICAL,
    OXYGEN_SATURATION_LOW,
    OXYGEN_SATURATION_RAPID_DROP,
    HYPOTENSIVE_HYPOXEMIA,
    ECG_ABNORMALITY,
    MANUAL_TRIGGER
}
